# Generated by Django 2.0.7 on 2018-07-14 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ('game_date',)},
        ),
        migrations.RemoveField(
            model_name='stadium',
            name='game',
        ),
        migrations.AddField(
            model_name='game',
            name='stadium',
            field=models.ForeignKey(default='9999', on_delete=django.db.models.deletion.CASCADE, related_name='games', to='visual.Stadium'),
        ),
    ]
