# Generated by Django 2.0.7 on 2018-07-14 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0002_auto_20180715_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='stadium',
            field=models.ForeignKey(default='9999', on_delete=django.db.models.deletion.CASCADE, related_name='games', to='visual.Stadium'),
        ),
    ]
