# Generated by Django 2.0.7 on 2018-07-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0003_auto_20180715_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stadium',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stadium',
            name='long',
            field=models.FloatField(),
        ),
    ]
