# Generated by Django 2.0.7 on 2018-07-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0005_stadium_stadium_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stadium',
            name='stadium_date',
            field=models.DateField(default='2018-06-14'),
        ),
    ]
